Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -46,8 +46,15 @@ jobs:
         tar -xf toolchains/clang.tar.gz -C toolchains/
 
         echo "Renaming directories..."
-        mv toolchains/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu toolchains/gcc
-        mv toolchains/clang-r450784e toolchains/clang
+        mv toolchains/arm-gnu-toolchain-* toolchains/gcc || true
+
+        echo "Checking Clang folder..."
+        if [ ! -d toolchains/clang ]; then
+          echo "ERROR: Clang folder not found after extraction!"
+          echo "Directory listing:"
+          ls -al toolchains
+          exit 1
+        fi
 
     - name: Export PATH
       run: |
